-- WhatsGrolink.com schema and seed data.
-- Create the database first, then import this file into it.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE admins (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(60) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(190) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_admins_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE password_resets (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  admin_id INT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_password_resets_token (token_hash),
  KEY idx_password_resets_admin (admin_id),
  CONSTRAINT fk_password_resets_admin FOREIGN KEY (admin_id) REFERENCES admins (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(160) NOT NULL,
  name_ur VARCHAR(160) NULL,
  slug VARCHAR(140) NOT NULL,
  kind ENUM('country', 'topic') NOT NULL DEFAULT 'topic',
  is_adult TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_categories_slug (slug),
  KEY idx_categories_kind (kind)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `groups` (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  invite_url VARCHAR(500) NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  description TEXT NOT NULL,
  image_url VARCHAR(500) NULL,
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_groups_invite (invite_url),
  KEY idx_groups_status (status),
  KEY idx_groups_category (category_id),
  CONSTRAINT fk_groups_category FOREIGN KEY (category_id) REFERENCES categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE reports (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_id INT UNSIGNED NOT NULL,
  reason VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_reports_group (group_id),
  CONSTRAINT fk_reports_group FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE messages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ad_slots (
  slot VARCHAR(20) NOT NULL,
  code MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (slot)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO admins (username, password_hash) VALUES ('admin', '$2y$10$taHMrjN4jUQ2lhikAOzsQuRiM7Dzb38ILpRbQVi3jcKFydR9HZBfS');

INSERT INTO ad_slots (slot, code) VALUES
('header', ''),
('home', ''),
('group', ''),
('footer', '');

INSERT INTO categories (name, name_ur, slug, kind) VALUES
('Afghanistan', 'افغانستان', 'afghanistan', 'country'),
('Albania', 'البانیا', 'albania', 'country'),
('Algeria', 'الجزائر', 'algeria', 'country'),
('Andorra', 'انڈورا', 'andorra', 'country'),
('Angola', 'انگولا', 'angola', 'country'),
('Antigua and Barbuda', 'اینٹیگوا و باربوڈا', 'antigua-and-barbuda', 'country'),
('Argentina', 'ارجنٹائن', 'argentina', 'country'),
('Armenia', 'آرمینیا', 'armenia', 'country'),
('Australia', 'آسٹریلیا', 'australia', 'country'),
('Austria', 'آسٹریا', 'austria', 'country'),
('Azerbaijan', 'آذربائیجان', 'azerbaijan', 'country'),
('Bahamas', 'بہاماس', 'bahamas', 'country'),
('Bahrain', 'بحرین', 'bahrain', 'country'),
('Bangladesh', 'بنگلہ دیش', 'bangladesh', 'country'),
('Barbados', 'بارباڈوس', 'barbados', 'country'),
('Belarus', 'بیلاروس', 'belarus', 'country'),
('Belgium', 'بیلجیم', 'belgium', 'country'),
('Belize', 'بیلیز', 'belize', 'country'),
('Benin', 'بینن', 'benin', 'country'),
('Bhutan', 'بھوٹان', 'bhutan', 'country'),
('Bolivia', 'بولیویا', 'bolivia', 'country'),
('Bosnia and Herzegovina', 'بوسنیا و ہرزیگووینا', 'bosnia-and-herzegovina', 'country'),
('Botswana', 'بوٹسوانا', 'botswana', 'country'),
('Brazil', 'برازیل', 'brazil', 'country'),
('Brunei', 'برونائی', 'brunei', 'country'),
('Bulgaria', 'بلغاریہ', 'bulgaria', 'country'),
('Burkina Faso', 'برکینا فاسو', 'burkina-faso', 'country'),
('Burundi', 'برونڈی', 'burundi', 'country'),
('Cabo Verde', 'کیپ ورڈی', 'cabo-verde', 'country'),
('Cambodia', 'کمبوڈیا', 'cambodia', 'country'),
('Cameroon', 'کیمرون', 'cameroon', 'country'),
('Canada', 'کینیڈا', 'canada', 'country'),
('Central African Republic', 'وسطی افریقی جمہوریہ', 'central-african-republic', 'country'),
('Chad', 'چاڈ', 'chad', 'country'),
('Chile', 'چلی', 'chile', 'country'),
('China', 'چین', 'china', 'country'),
('Colombia', 'کولمبیا', 'colombia', 'country'),
('Comoros', 'کوموروس', 'comoros', 'country'),
('Congo', 'کانگو', 'congo', 'country'),
('Costa Rica', 'کوسٹا ریکا', 'costa-rica', 'country'),
('Cote d''Ivoire', 'آئیوری کوسٹ', 'cote-divoire', 'country'),
('Croatia', 'کروشیا', 'croatia', 'country'),
('Cuba', 'کیوبا', 'cuba', 'country'),
('Cyprus', 'قبرص', 'cyprus', 'country'),
('Czechia', 'چیکیا', 'czechia', 'country'),
('Democratic Republic of the Congo', 'جمہوری جمہوریہ کانگو', 'democratic-republic-of-the-congo', 'country'),
('Denmark', 'ڈنمارک', 'denmark', 'country'),
('Djibouti', 'جبوتی', 'djibouti', 'country'),
('Dominica', 'ڈومینیکا', 'dominica', 'country'),
('Dominican Republic', 'ڈومینیکن جمہوریہ', 'dominican-republic', 'country'),
('Ecuador', 'ایکواڈور', 'ecuador', 'country'),
('Egypt', 'مصر', 'egypt', 'country'),
('El Salvador', 'ایل سلواڈور', 'el-salvador', 'country'),
('Equatorial Guinea', 'استوائی گنی', 'equatorial-guinea', 'country'),
('Eritrea', 'اریٹیریا', 'eritrea', 'country'),
('Estonia', 'اسٹونیا', 'estonia', 'country'),
('Eswatini', 'ایسواتینی', 'eswatini', 'country'),
('Ethiopia', 'ایتھوپیا', 'ethiopia', 'country'),
('Fiji', 'فجی', 'fiji', 'country'),
('Finland', 'فن لینڈ', 'finland', 'country'),
('France', 'فرانس', 'france', 'country'),
('Gabon', 'گیبون', 'gabon', 'country'),
('Gambia', 'گیمبیا', 'gambia', 'country'),
('Georgia', 'جارجیا', 'georgia', 'country'),
('Germany', 'جرمنی', 'germany', 'country'),
('Ghana', 'گھانا', 'ghana', 'country'),
('Greece', 'یونان', 'greece', 'country'),
('Grenada', 'گریناڈا', 'grenada', 'country'),
('Guatemala', 'گواتیمالا', 'guatemala', 'country'),
('Guinea', 'گنی', 'guinea', 'country'),
('Guinea-Bissau', 'گنی بساؤ', 'guinea-bissau', 'country'),
('Guyana', 'گیانا', 'guyana', 'country'),
('Haiti', 'ہیٹی', 'haiti', 'country'),
('Honduras', 'ہونڈوراس', 'honduras', 'country'),
('Hungary', 'ہنگری', 'hungary', 'country'),
('Iceland', 'آئس لینڈ', 'iceland', 'country'),
('India', 'بھارت', 'india', 'country'),
('Indonesia', 'انڈونیشیا', 'indonesia', 'country'),
('Iran', 'ایران', 'iran', 'country'),
('Iraq', 'عراق', 'iraq', 'country'),
('Ireland', 'آئرلینڈ', 'ireland', 'country'),
('Israel', 'اسرائیل', 'israel', 'country'),
('Italy', 'اٹلی', 'italy', 'country'),
('Jamaica', 'جمیکا', 'jamaica', 'country'),
('Japan', 'جاپان', 'japan', 'country'),
('Jordan', 'اردن', 'jordan', 'country'),
('Kazakhstan', 'قازقستان', 'kazakhstan', 'country'),
('Kenya', 'کینیا', 'kenya', 'country'),
('Kiribati', NULL, 'kiribati', 'country'),
('Kosovo', 'کوسوو', 'kosovo', 'country'),
('Kuwait', 'کویت', 'kuwait', 'country'),
('Kyrgyzstan', 'کرغزستان', 'kyrgyzstan', 'country'),
('Laos', 'لاؤس', 'laos', 'country'),
('Latvia', 'لٹویا', 'latvia', 'country'),
('Lebanon', 'لبنان', 'lebanon', 'country'),
('Lesotho', 'لیسوتھو', 'lesotho', 'country'),
('Liberia', 'لائبیریا', 'liberia', 'country'),
('Libya', 'لیبیا', 'libya', 'country'),
('Liechtenstein', 'لیختینستائن', 'liechtenstein', 'country'),
('Lithuania', 'لتھوانیا', 'lithuania', 'country'),
('Luxembourg', 'لکسمبرگ', 'luxembourg', 'country'),
('Madagascar', 'مڈغاسکر', 'madagascar', 'country'),
('Malawi', 'ملاوی', 'malawi', 'country'),
('Malaysia', 'ملائیشیا', 'malaysia', 'country'),
('Maldives', 'مالدیپ', 'maldives', 'country'),
('Mali', 'مالی', 'mali', 'country'),
('Malta', 'مالٹا', 'malta', 'country'),
('Marshall Islands', NULL, 'marshall-islands', 'country'),
('Mauritania', 'موریتانیہ', 'mauritania', 'country'),
('Mauritius', 'ماریشس', 'mauritius', 'country'),
('Mexico', 'میکسیکو', 'mexico', 'country'),
('Micronesia', NULL, 'micronesia', 'country'),
('Moldova', 'مالدووا', 'moldova', 'country'),
('Monaco', 'موناکو', 'monaco', 'country'),
('Mongolia', 'منگولیا', 'mongolia', 'country'),
('Montenegro', 'مونٹینیگرو', 'montenegro', 'country'),
('Morocco', 'مراکش', 'morocco', 'country'),
('Mozambique', 'موزمبیق', 'mozambique', 'country'),
('Myanmar', 'میانمار', 'myanmar', 'country'),
('Namibia', 'نمیبیا', 'namibia', 'country'),
('Nauru', NULL, 'nauru', 'country'),
('Nepal', 'نیپال', 'nepal', 'country'),
('Netherlands', 'نیدرلینڈز', 'netherlands', 'country'),
('New Zealand', 'نیوزی لینڈ', 'new-zealand', 'country'),
('Nicaragua', 'نکاراگوا', 'nicaragua', 'country'),
('Niger', 'نائجر', 'niger', 'country'),
('Nigeria', 'نائجیریا', 'nigeria', 'country'),
('North Korea', 'شمالی کوریا', 'north-korea', 'country'),
('North Macedonia', 'شمالی مقدونیہ', 'north-macedonia', 'country'),
('Norway', 'ناروے', 'norway', 'country'),
('Oman', 'عمان', 'oman', 'country'),
('Pakistan', 'پاکستان', 'pakistan', 'country'),
('Palau', NULL, 'palau', 'country'),
('Palestine', 'فلسطین', 'palestine', 'country'),
('Panama', 'پاناما', 'panama', 'country'),
('Papua New Guinea', 'پاپوا نیو گنی', 'papua-new-guinea', 'country'),
('Paraguay', 'پیراگوئے', 'paraguay', 'country'),
('Peru', 'پیرو', 'peru', 'country'),
('Philippines', 'فلپائن', 'philippines', 'country'),
('Poland', 'پولینڈ', 'poland', 'country'),
('Portugal', 'پرتگال', 'portugal', 'country'),
('Qatar', 'قطر', 'qatar', 'country'),
('Romania', 'رومانیہ', 'romania', 'country'),
('Russia', 'روس', 'russia', 'country'),
('Rwanda', 'روانڈا', 'rwanda', 'country'),
('Saint Kitts and Nevis', NULL, 'saint-kitts-and-nevis', 'country'),
('Saint Lucia', NULL, 'saint-lucia', 'country'),
('Saint Vincent and the Grenadines', NULL, 'saint-vincent-and-the-grenadines', 'country'),
('Samoa', 'ساموا', 'samoa', 'country'),
('San Marino', 'سان مارینو', 'san-marino', 'country'),
('Sao Tome and Principe', NULL, 'sao-tome-and-principe', 'country'),
('Saudi Arabia', 'سعودی عرب', 'saudi-arabia', 'country'),
('Senegal', 'سینیگال', 'senegal', 'country'),
('Serbia', 'سربیا', 'serbia', 'country'),
('Seychelles', 'سیشلز', 'seychelles', 'country'),
('Sierra Leone', 'سیرا لیون', 'sierra-leone', 'country'),
('Singapore', 'سنگاپور', 'singapore', 'country'),
('Slovakia', 'سلوواکیہ', 'slovakia', 'country'),
('Slovenia', 'سلووینیا', 'slovenia', 'country'),
('Solomon Islands', NULL, 'solomon-islands', 'country'),
('Somalia', 'صومالیہ', 'somalia', 'country'),
('South Africa', 'جنوبی افریقہ', 'south-africa', 'country'),
('South Korea', 'جنوبی کوریا', 'south-korea', 'country'),
('South Sudan', 'جنوبی سوڈان', 'south-sudan', 'country'),
('Spain', 'سپین', 'spain', 'country'),
('Sri Lanka', 'سری لنکا', 'sri-lanka', 'country'),
('Sudan', 'سوڈان', 'sudan', 'country'),
('Suriname', 'سورینام', 'suriname', 'country'),
('Sweden', 'سویڈن', 'sweden', 'country'),
('Switzerland', 'سوئٹزرلینڈ', 'switzerland', 'country'),
('Syria', 'شام', 'syria', 'country'),
('Taiwan', 'تائیوان', 'taiwan', 'country'),
('Tajikistan', 'تاجکستان', 'tajikistan', 'country'),
('Tanzania', 'تنزانیہ', 'tanzania', 'country'),
('Thailand', 'تھائی لینڈ', 'thailand', 'country'),
('Timor-Leste', 'مشرقی تیمور', 'timor-leste', 'country'),
('Togo', 'ٹوگو', 'togo', 'country'),
('Tonga', 'ٹونگا', 'tonga', 'country'),
('Trinidad and Tobago', 'ٹرینیڈاڈ و ٹوباگو', 'trinidad-and-tobago', 'country'),
('Tunisia', 'تیونس', 'tunisia', 'country'),
('Turkey', 'ترکی', 'turkey', 'country'),
('Turkmenistan', 'ترکمانستان', 'turkmenistan', 'country'),
('Tuvalu', NULL, 'tuvalu', 'country'),
('Uganda', 'یوگنڈا', 'uganda', 'country'),
('Ukraine', 'یوکرین', 'ukraine', 'country'),
('United Arab Emirates', 'متحدہ عرب امارات', 'united-arab-emirates', 'country'),
('United Kingdom', 'برطانیہ', 'united-kingdom', 'country'),
('United States', 'امریکہ', 'united-states', 'country'),
('Uruguay', 'یوراگوئے', 'uruguay', 'country'),
('Uzbekistan', 'ازبکستان', 'uzbekistan', 'country'),
('Vanuatu', NULL, 'vanuatu', 'country'),
('Vatican City', 'ویٹیکن', 'vatican-city', 'country'),
('Venezuela', 'وینزویلا', 'venezuela', 'country'),
('Vietnam', 'ویتنام', 'vietnam', 'country'),
('Yemen', 'یمن', 'yemen', 'country'),
('Zambia', 'زیمبیا', 'zambia', 'country'),
('Zimbabwe', 'زمبابوے', 'zimbabwe', 'country'),
('Friendship', 'دوستی', 'friendship', 'topic'),
('Friends', 'دوست', 'friends', 'topic'),
('Chat', 'چیٹ', 'chat', 'topic'),
('Dating', 'ڈیٹنگ', 'dating', 'topic'),
('Marriage', 'شادی', 'marriage', 'topic'),
('Matrimony', 'رشتہ ازدواج', 'matrimony', 'topic'),
('Relationship', 'رشتے', 'relationship', 'topic'),
('Family', 'خاندان', 'family', 'topic'),
('Women', 'خواتین', 'women', 'topic'),
('Men', 'مرد', 'men', 'topic'),
('Singles', 'سنگلز', 'singles', 'topic'),
('Pen Pal', 'قلمی دوست', 'pen-pal', 'topic'),
('Jobs', 'ملازمتیں', 'jobs', 'topic'),
('Job Alerts', 'ملازمت الرٹس', 'job-alerts', 'topic'),
('Government Jobs', 'سرکاری نوکریاں', 'government-jobs', 'topic'),
('Private Jobs', 'پرائیویٹ نوکریاں', 'private-jobs', 'topic'),
('Part Time', 'پارٹ ٹائم', 'part-time', 'topic'),
('Work From Home', 'گھر سے کام', 'work-from-home', 'topic'),
('Freelance', 'فری لانس', 'freelance', 'topic'),
('Internships', 'انٹرنشپ', 'internships', 'topic'),
('Teaching Jobs', 'تدریسی نوکریاں', 'teaching-jobs', 'topic'),
('Police Jobs', 'پولیس نوکریاں', 'police-jobs', 'topic'),
('Army Jobs', 'فوجی بھرتی', 'army-jobs', 'topic'),
('Bank Jobs', 'بینک نوکریاں', 'bank-jobs', 'topic'),
('Online Earning', 'آن لائن کمائی', 'online-earning', 'topic'),
('Referrals', 'ریفرل', 'referrals', 'topic'),
('Business', 'کاروبار', 'business', 'topic'),
('Buy and Sell', 'خرید و فروخت', 'buy-sell', 'topic'),
('Marketing', 'مارکیٹنگ', 'marketing', 'topic'),
('Digital Marketing', 'ڈیجیٹل مارکیٹنگ', 'digital-marketing', 'topic'),
('Ecommerce', 'ای کامرس', 'ecommerce', 'topic'),
('Startups', 'سٹارٹ اپ', 'startups', 'topic'),
('Entrepreneurship', 'کاروبار شروع کریں', 'entrepreneurship', 'topic'),
('Networking', 'نیٹ ورکنگ', 'networking', 'topic'),
('Investment', 'سرمایہ کاری', 'investment', 'topic'),
('Stock Market', 'شیئر مارکیٹ', 'stock-market', 'topic'),
('Trading', 'ٹریڈنگ', 'trading', 'topic'),
('Forex', 'فاریکس', 'forex', 'topic'),
('Crypto', 'کرپٹو', 'crypto', 'topic'),
('Bitcoin', 'بٹ کوائن', 'bitcoin', 'topic'),
('Real Estate', 'جائیداد', 'real-estate', 'topic'),
('Dropshipping', 'ڈراپ شپنگ', 'dropshipping', 'topic'),
('Classifieds', 'اشتہارات', 'classifieds', 'topic'),
('Deals', 'ڈیلز', 'deals', 'topic'),
('Wholesale', 'تھوک', 'wholesale', 'topic'),
('Import Export', 'درآمد برآمد', 'import-export', 'topic'),
('Education', 'تعلیم', 'education', 'topic'),
('Students', 'طلبہ', 'students', 'topic'),
('Exams', 'امتحانات', 'exams', 'topic'),
('Study', 'مطالعہ', 'study', 'topic'),
('Scholarships', 'وظائف', 'scholarships', 'topic'),
('University', 'یونیورسٹی', 'university', 'topic'),
('English Speaking', 'انگلش بولیں', 'english-speaking', 'topic'),
('Language Learning', 'زبان سیکھیں', 'language-learning', 'topic'),
('Study Abroad', 'بیرون ملک تعلیم', 'study-abroad', 'topic'),
('IELTS', 'آئی ایلٹس', 'ielts', 'topic'),
('CSS Exam', 'سی ایس ایس', 'css-exam', 'topic'),
('PPSC', 'پی پی ایس سی', 'ppsc', 'topic'),
('FPSC', 'ایف پی ایس سی', 'fpsc', 'topic'),
('UPSC', 'یو پی ایس سی', 'upsc', 'topic'),
('SSC', 'ایس ایس سی', 'ssc', 'topic'),
('NEET', 'نیٹ', 'neet', 'topic'),
('JEE', 'جے ای ای', 'jee', 'topic'),
('Engineering', 'انجینئرنگ', 'engineering', 'topic'),
('Medical', 'میڈیکل', 'medical', 'topic'),
('Nursing', 'نرسنگ', 'nursing', 'topic'),
('Books', 'کتابیں', 'books', 'topic'),
('Science', 'سائنس', 'science', 'topic'),
('History', 'تاریخ', 'history', 'topic'),
('General Knowledge', 'جنرل نالج', 'general-knowledge', 'topic'),
('Teachers', 'اساتذہ', 'teachers', 'topic'),
('Motivation', 'حوصلہ', 'motivation', 'topic'),
('News', 'خبریں', 'news', 'topic'),
('Breaking News', 'بریکنگ نیوز', 'breaking-news', 'topic'),
('Politics', 'سیاست', 'politics', 'topic'),
('Local News', 'مقامی خبریں', 'local-news', 'topic'),
('World News', 'عالمی خبریں', 'world-news', 'topic'),
('Weather', 'موسم', 'weather', 'topic'),
('Alerts', 'الرٹس', 'alerts', 'topic'),
('Sports', 'کھیل', 'sports', 'topic'),
('Cricket', 'کرکٹ', 'cricket', 'topic'),
('Football', 'فٹبال', 'football', 'topic'),
('Basketball', 'باسکٹ بال', 'basketball', 'topic'),
('Tennis', 'ٹینس', 'tennis', 'topic'),
('Hockey', 'ہاکی', 'hockey', 'topic'),
('Kabaddi', 'کبڈی', 'kabaddi', 'topic'),
('Wrestling', 'کشتی', 'wrestling', 'topic'),
('Boxing', 'باکسنگ', 'boxing', 'topic'),
('Fitness', 'فٹنس', 'fitness', 'topic'),
('Gym', 'جم', 'gym', 'topic'),
('IPL', 'آئی پی ایل', 'ipl', 'topic'),
('PSL', 'پی ایس ایل', 'psl', 'topic'),
('World Cup', 'ورلڈ کپ', 'world-cup', 'topic'),
('Premier League', 'پریمیئر لیگ', 'premier-league', 'topic'),
('Olympics', 'اولمپکس', 'olympics', 'topic'),
('Esports', 'ای اسپورٹس', 'esports', 'topic'),
('Chess', 'شطرنج', 'chess', 'topic'),
('Health', 'صحت', 'health', 'topic'),
('Yoga', 'یوگا', 'yoga', 'topic'),
('Doctors', 'ڈاکٹرز', 'doctors', 'topic'),
('Weight Loss', 'وزن کم کریں', 'weight-loss', 'topic'),
('Diet', 'غذا', 'diet', 'topic'),
('Mental Health', 'ذہنی صحت', 'mental-health', 'topic'),
('Meditation', 'مراقبہ', 'meditation', 'topic'),
('Pregnancy', 'حمل', 'pregnancy', 'topic'),
('Parenting', 'والدین', 'parenting', 'topic'),
('Blood Donors', 'خون کے عطیات', 'blood-donors', 'topic'),
('Gaming', 'گیمنگ', 'gaming', 'topic'),
('PUBG', 'پب جی', 'pubg', 'topic'),
('Free Fire', 'فری فائر', 'free-fire', 'topic'),
('Mobile Legends', 'موبائل لیجنڈز', 'mobile-legends', 'topic'),
('Call of Duty', 'کال آف ڈیوٹی', 'call-of-duty', 'topic'),
('Minecraft', 'مائن کرافٹ', 'minecraft', 'topic'),
('Valorant', 'ویلورنٹ', 'valorant', 'topic'),
('Ludo', 'لڈو', 'ludo', 'topic'),
('Status', 'اسٹیٹس', 'status', 'topic'),
('WhatsApp Status', 'واٹس ایپ اسٹیٹس', 'whatsapp-status', 'topic'),
('Jokes', 'لطیفے', 'jokes', 'topic'),
('Shayari', 'شاعری', 'shayari', 'topic'),
('Poetry', 'نظم', 'poetry', 'topic'),
('Quotes', 'اقوال', 'quotes', 'topic'),
('Memes', 'میمز', 'memes', 'topic'),
('Funny', 'مزاح', 'funny', 'topic'),
('Good Morning', 'گڈ مارننگ', 'good-morning', 'topic'),
('Good Night', 'گڈ نائٹ', 'good-night', 'topic'),
('Greetings', 'سلام دعا', 'greetings', 'topic'),
('Birthday', 'سالگرہ', 'birthday', 'topic'),
('Stickers', 'سٹیکرز', 'stickers', 'topic'),
('Wallpapers', 'وال پیپر', 'wallpapers', 'topic'),
('Facts', 'حقائق', 'facts', 'topic'),
('Stories', 'کہانیاں', 'stories', 'topic'),
('Novels', 'ناول', 'novels', 'topic'),
('Islamic', 'اسلامی', 'islamic', 'topic'),
('Quran', 'قرآن', 'quran', 'topic'),
('Hadith', 'حدیث', 'hadith', 'topic'),
('Namaz', 'نماز', 'namaz', 'topic'),
('Dua', 'دعا', 'dua', 'topic'),
('Naat', 'نعت', 'naat', 'topic'),
('Tajweed', 'تجوید', 'tajweed', 'topic'),
('Ramadan', 'رمضان', 'ramadan', 'topic'),
('Eid', 'عید', 'eid', 'topic'),
('Islamic Lectures', 'اسلامی لیکچرز', 'islamic-lectures', 'topic'),
('Christianity', 'عیسائیت', 'christianity', 'topic'),
('Bible', 'بائبل', 'bible', 'topic'),
('Hinduism', 'ہندو مت', 'hinduism', 'topic'),
('Buddhism', 'بدھ مت', 'buddhism', 'topic'),
('Sikhism', 'سکھ مت', 'sikhism', 'topic'),
('Entertainment', 'تفریح', 'entertainment', 'topic'),
('Movies', 'فلمیں', 'movies', 'topic'),
('Songs', 'گانے', 'songs', 'topic'),
('Music', 'موسیقی', 'music', 'topic'),
('Bollywood', 'بالی ووڈ', 'bollywood', 'topic'),
('Hollywood', 'ہالی ووڈ', 'hollywood', 'topic'),
('Lollywood', 'لالی ووڈ', 'lollywood', 'topic'),
('Drama', 'ڈرامہ', 'drama', 'topic'),
('Celebrity', 'مشہور شخصیات', 'celebrity', 'topic'),
('Viral', 'وائرل', 'viral', 'topic'),
('Trending', 'ٹرینڈنگ', 'trending', 'topic'),
('Anime', 'اینیمے', 'anime', 'topic'),
('YouTube', 'یوٹیوب', 'youtube', 'topic'),
('Technology', 'ٹیکنالوجی', 'technology', 'topic'),
('Programming', 'پروگرامنگ', 'programming', 'topic'),
('Android', 'اینڈرائیڈ', 'android', 'topic'),
('iPhone', 'آئی فون', 'iphone', 'topic'),
('Computers', 'کمپیوٹر', 'computers', 'topic'),
('Artificial Intelligence', 'مصنوعی ذہانت', 'artificial-intelligence', 'topic'),
('Gadgets', 'گیجٹس', 'gadgets', 'topic'),
('SEO', 'ایس ای او', 'seo', 'topic'),
('Blogging', 'بلاگنگ', 'blogging', 'topic'),
('Video Editing', 'ویڈیو ایڈیٹنگ', 'video-editing', 'topic'),
('Graphic Design', 'گرافک ڈیزائن', 'graphic-design', 'topic'),
('Photography', 'فوٹوگرافی', 'photography', 'topic'),
('Design', 'ڈیزائن', 'design', 'topic'),
('Cooking', 'کھانا پکانا', 'cooking', 'topic'),
('Recipes', 'ترکیبیں', 'recipes', 'topic'),
('Food', 'کھانا', 'food', 'topic'),
('Travel', 'سفر', 'travel', 'topic'),
('Tourism', 'سیاحت', 'tourism', 'topic'),
('Cars', 'گاڑیاں', 'cars', 'topic'),
('Bikes', 'موٹر سائیکل', 'bikes', 'topic'),
('Fashion', 'فیشن', 'fashion', 'topic'),
('Beauty', 'بیوٹی', 'beauty', 'topic'),
('Shopping', 'شاپنگ', 'shopping', 'topic'),
('Pets', 'پالتو جانور', 'pets', 'topic'),
('Visa', 'ویزا', 'visa', 'topic'),
('Immigration', 'امیگریشن', 'immigration', 'topic'),
('OFW', 'او ایف ڈبلیو', 'ofw', 'topic'),
('Banking', 'بینکنگ', 'banking', 'topic'),
('Insurance', 'انشورنس', 'insurance', 'topic'),
('Legal', 'قانونی', 'legal', 'topic'),
('Lawyers', 'وکلاء', 'lawyers', 'topic'),
('Rent', 'کرایہ', 'rent', 'topic'),
('Roommates', 'روم میٹ', 'roommates', 'topic'),
('Events', 'پروگرام', 'events', 'topic'),
('Charity', 'خیرات', 'charity', 'topic'),
('Volunteers', 'رضاکار', 'volunteers', 'topic'),
('Agriculture', 'زراعت', 'agriculture', 'topic'),
('Farming', 'کاشتکاری', 'farming', 'topic'),
('Environment', 'ماحول', 'environment', 'topic'),
('Lost and Found', 'گمشدہ و دریافت', 'lost-found', 'topic'),
('Traffic', 'ٹریفک', 'traffic', 'topic'),
('Services', 'خدمات', 'services', 'topic'),
('Translation', 'ترجمہ', 'translation', 'topic'),
('Customer Support', 'کسٹمر سپورٹ', 'customer-support', 'topic'),
('Property', 'پراپرٹی', 'property', 'topic'),
('Coupons', 'کوپن', 'coupons', 'topic'),
('Giveaways', 'گفٹ', 'giveaways', 'topic'),
('City Groups', 'شہر کے گروپ', 'city-groups', 'topic'),
('Neighborhood', 'محلہ', 'neighborhood', 'topic'),
('Carpool', 'کار پول', 'carpool', 'topic'),
('Daraz', 'داراز', 'daraz', 'topic'),
('OLX', 'اولیکس', 'olx', 'topic'),
('Amazon', 'ایمیزون', 'amazon', 'topic'),
('Adsense', 'ایڈسینس', 'adsense', 'topic'),
('Affiliate', 'ایفیلیئیٹ', 'affiliate', 'topic'),
('Handmade', 'دستکاری', 'handmade', 'topic'),
('Art', 'آرٹ', 'art', 'topic'),
('Drawing', 'ڈرائنگ', 'drawing', 'topic'),
('Urdu Poetry', 'اردو شاعری', 'urdu-poetry', 'topic'),
('Good Morning Images', 'گڈ مارننگ تصاویر', 'good-morning-images', 'topic'),
('DP Images', 'ڈسپلے پکچر', 'dp-images', 'topic'),
('Ringtones', 'رنگ ٹون', 'ringtones', 'topic'),
('Pharmacy', 'فارمیسی', 'pharmacy', 'topic'),
('Mechanics', 'مکینکس', 'mechanics', 'topic'),
('Drivers', 'ڈرائیور', 'drivers', 'topic'),
('Delivery', 'ڈیلیوری', 'delivery', 'topic'),
('Restaurants', 'ریستوراں', 'restaurants', 'topic'),
('Hotels', 'ہوٹل', 'hotels', 'topic'),
('Flights', 'پروازیں', 'flights', 'topic'),
('Currency', 'کرنسی', 'currency', 'topic'),
('Gold Rate', 'سونے کا ریٹ', 'gold-rate', 'topic'),
('Fuel Prices', 'پیٹرول قیمت', 'fuel-prices', 'topic'),
('Results', 'رزلٹ', 'results', 'topic'),
('Admissions', 'داخلے', 'admissions', 'topic'),
('Coding', 'کوڈنگ', 'coding', 'topic'),
('Python', 'پائتھن', 'python', 'topic'),
('Web Development', 'ویب ڈیولپمنٹ', 'web-development', 'topic'),
('Cybersecurity', 'سائبر سیکیورٹی', 'cybersecurity', 'topic'),
('Mobile Phones', 'موبائل فون', 'mobile-phones', 'topic'),
('Laptop', 'لیپ ٹاپ', 'laptop', 'topic'),
('Islamabad', 'اسلام آباد', 'islamabad', 'topic'),
('Karachi', 'کراچی', 'karachi', 'topic'),
('Lahore', 'لاہور', 'lahore', 'topic'),
('Delhi', 'دہلی', 'delhi', 'topic'),
('Mumbai', 'ممبئی', 'mumbai', 'topic'),
('Dhaka', 'ڈھاکہ', 'dhaka', 'topic'),
('Lagos', 'لاگوس', 'lagos', 'topic'),
('Dubai', 'دبئی', 'dubai', 'topic'),
('Riyadh', 'ریاض', 'riyadh', 'topic'),
('Jeddah', 'جدہ', 'jeddah', 'topic'),
('Cairo', 'قاہرہ', 'cairo', 'topic'),
('Istanbul', 'استنبول', 'istanbul', 'topic'),
('Jakarta', 'جکارتہ', 'jakarta', 'topic'),
('Manila', 'منیلا', 'manila', 'topic'),
('London', 'لندن', 'london', 'topic'),
('New York', 'نیو یارک', 'new-york', 'topic'),
('Pakistan Friendship', 'پاکستان دوستی', 'pakistan-friendship', 'topic'),
('Pakistan Jobs', 'پاکستان ملازمتیں', 'pakistan-jobs', 'topic'),
('Pakistan News', 'پاکستان خبریں', 'pakistan-news', 'topic'),
('Pakistan Education', 'پاکستان تعلیم', 'pakistan-education', 'topic'),
('Pakistan Business', 'پاکستان کاروبار', 'pakistan-business', 'topic'),
('Pakistan Sports', 'پاکستان کھیل', 'pakistan-sports', 'topic'),
('Pakistan Gaming', 'پاکستان گیمنگ', 'pakistan-gaming', 'topic'),
('Pakistan Status', 'پاکستان اسٹیٹس', 'pakistan-status', 'topic'),
('Pakistan Cricket', 'پاکستان کرکٹ', 'pakistan-cricket', 'topic'),
('Pakistan Islamic', 'پاکستان اسلامی', 'pakistan-islamic', 'topic'),
('Pakistan Shayari', 'پاکستان شاعری', 'pakistan-shayari', 'topic'),
('Pakistan PUBG', 'پاکستان پب جی', 'pakistan-pubg', 'topic'),
('Pakistan Government Jobs', 'پاکستان سرکاری نوکریاں', 'pakistan-government-jobs', 'topic'),
('India Friendship', 'بھارت دوستی', 'india-friendship', 'topic'),
('India Jobs', 'بھارت ملازمتیں', 'india-jobs', 'topic'),
('India News', 'بھارت خبریں', 'india-news', 'topic'),
('India Education', 'بھارت تعلیم', 'india-education', 'topic'),
('India Business', 'بھارت کاروبار', 'india-business', 'topic'),
('India Sports', 'بھارت کھیل', 'india-sports', 'topic'),
('India Gaming', 'بھارت گیمنگ', 'india-gaming', 'topic'),
('India Status', 'بھارت اسٹیٹس', 'india-status', 'topic'),
('India Cricket', 'بھارت کرکٹ', 'india-cricket', 'topic'),
('India Shayari', 'بھارت شاعری', 'india-shayari', 'topic'),
('India Bollywood', 'بھارت بالی ووڈ', 'india-bollywood', 'topic'),
('India PUBG', 'بھارت پب جی', 'india-pubg', 'topic'),
('India Government Jobs', 'بھارت سرکاری نوکریاں', 'india-government-jobs', 'topic'),
('Bangladesh Friendship', 'بنگلہ دیش دوستی', 'bangladesh-friendship', 'topic'),
('Bangladesh Jobs', 'بنگلہ دیش ملازمتیں', 'bangladesh-jobs', 'topic'),
('Bangladesh News', 'بنگلہ دیش خبریں', 'bangladesh-news', 'topic'),
('Bangladesh Education', 'بنگلہ دیش تعلیم', 'bangladesh-education', 'topic'),
('Bangladesh Business', 'بنگلہ دیش کاروبار', 'bangladesh-business', 'topic'),
('Bangladesh Sports', 'بنگلہ دیش کھیل', 'bangladesh-sports', 'topic'),
('Bangladesh Gaming', 'بنگلہ دیش گیمنگ', 'bangladesh-gaming', 'topic'),
('Bangladesh Status', 'بنگلہ دیش اسٹیٹس', 'bangladesh-status', 'topic'),
('Bangladesh Cricket', 'بنگلہ دیش کرکٹ', 'bangladesh-cricket', 'topic'),
('Bangladesh Islamic', 'بنگلہ دیش اسلامی', 'bangladesh-islamic', 'topic'),
('Indonesia Friendship', 'انڈونیشیا دوستی', 'indonesia-friendship', 'topic'),
('Indonesia Jobs', 'انڈونیشیا ملازمتیں', 'indonesia-jobs', 'topic'),
('Indonesia News', 'انڈونیشیا خبریں', 'indonesia-news', 'topic'),
('Indonesia Education', 'انڈونیشیا تعلیم', 'indonesia-education', 'topic'),
('Indonesia Business', 'انڈونیشیا کاروبار', 'indonesia-business', 'topic'),
('Indonesia Sports', 'انڈونیشیا کھیل', 'indonesia-sports', 'topic'),
('Indonesia Gaming', 'انڈونیشیا گیمنگ', 'indonesia-gaming', 'topic'),
('Indonesia Status', 'انڈونیشیا اسٹیٹس', 'indonesia-status', 'topic'),
('Indonesia Islamic', 'انڈونیشیا اسلامی', 'indonesia-islamic', 'topic'),
('Indonesia Buy and Sell', 'انڈونیشیا خرید و فروخت', 'indonesia-buy-sell', 'topic'),
('Nigeria Friendship', 'نائجیریا دوستی', 'nigeria-friendship', 'topic'),
('Nigeria Jobs', 'نائجیریا ملازمتیں', 'nigeria-jobs', 'topic'),
('Nigeria News', 'نائجیریا خبریں', 'nigeria-news', 'topic'),
('Nigeria Education', 'نائجیریا تعلیم', 'nigeria-education', 'topic'),
('Nigeria Business', 'نائجیریا کاروبار', 'nigeria-business', 'topic'),
('Nigeria Sports', 'نائجیریا کھیل', 'nigeria-sports', 'topic'),
('Nigeria Gaming', 'نائجیریا گیمنگ', 'nigeria-gaming', 'topic'),
('Nigeria Status', 'نائجیریا اسٹیٹس', 'nigeria-status', 'topic'),
('Nigeria Football', 'نائجیریا فٹبال', 'nigeria-football', 'topic'),
('Nigeria Crypto', 'نائجیریا کرپٹو', 'nigeria-crypto', 'topic'),
('Brazil Friendship', 'برازیل دوستی', 'brazil-friendship', 'topic'),
('Brazil Jobs', 'برازیل ملازمتیں', 'brazil-jobs', 'topic'),
('Brazil News', 'برازیل خبریں', 'brazil-news', 'topic'),
('Brazil Education', 'برازیل تعلیم', 'brazil-education', 'topic'),
('Brazil Business', 'برازیل کاروبار', 'brazil-business', 'topic'),
('Brazil Sports', 'برازیل کھیل', 'brazil-sports', 'topic'),
('Brazil Gaming', 'برازیل گیمنگ', 'brazil-gaming', 'topic'),
('Brazil Status', 'برازیل اسٹیٹس', 'brazil-status', 'topic'),
('Brazil Football', 'برازیل فٹبال', 'brazil-football', 'topic'),
('United States Friendship', 'امریکہ دوستی', 'united-states-friendship', 'topic'),
('United States Jobs', 'امریکہ ملازمتیں', 'united-states-jobs', 'topic'),
('United States News', 'امریکہ خبریں', 'united-states-news', 'topic'),
('United States Education', 'امریکہ تعلیم', 'united-states-education', 'topic'),
('United States Business', 'امریکہ کاروبار', 'united-states-business', 'topic'),
('United States Sports', 'امریکہ کھیل', 'united-states-sports', 'topic'),
('United States Gaming', 'امریکہ گیمنگ', 'united-states-gaming', 'topic'),
('United States Status', 'امریکہ اسٹیٹس', 'united-states-status', 'topic'),
('United States Technology', 'امریکہ ٹیکنالوجی', 'united-states-technology', 'topic'),
('United States Crypto', 'امریکہ کرپٹو', 'united-states-crypto', 'topic'),
('United Kingdom Friendship', 'برطانیہ دوستی', 'united-kingdom-friendship', 'topic'),
('United Kingdom Jobs', 'برطانیہ ملازمتیں', 'united-kingdom-jobs', 'topic'),
('United Kingdom News', 'برطانیہ خبریں', 'united-kingdom-news', 'topic'),
('United Kingdom Education', 'برطانیہ تعلیم', 'united-kingdom-education', 'topic'),
('United Kingdom Business', 'برطانیہ کاروبار', 'united-kingdom-business', 'topic'),
('United Kingdom Sports', 'برطانیہ کھیل', 'united-kingdom-sports', 'topic'),
('United Kingdom Gaming', 'برطانیہ گیمنگ', 'united-kingdom-gaming', 'topic'),
('United Kingdom Status', 'برطانیہ اسٹیٹس', 'united-kingdom-status', 'topic'),
('United Kingdom Football', 'برطانیہ فٹبال', 'united-kingdom-football', 'topic'),
('United Arab Emirates Friendship', 'متحدہ عرب امارات دوستی', 'united-arab-emirates-friendship', 'topic'),
('United Arab Emirates Jobs', 'متحدہ عرب امارات ملازمتیں', 'united-arab-emirates-jobs', 'topic'),
('United Arab Emirates News', 'متحدہ عرب امارات خبریں', 'united-arab-emirates-news', 'topic'),
('United Arab Emirates Education', 'متحدہ عرب امارات تعلیم', 'united-arab-emirates-education', 'topic'),
('United Arab Emirates Business', 'متحدہ عرب امارات کاروبار', 'united-arab-emirates-business', 'topic'),
('United Arab Emirates Sports', 'متحدہ عرب امارات کھیل', 'united-arab-emirates-sports', 'topic'),
('United Arab Emirates Gaming', 'متحدہ عرب امارات گیمنگ', 'united-arab-emirates-gaming', 'topic'),
('United Arab Emirates Status', 'متحدہ عرب امارات اسٹیٹس', 'united-arab-emirates-status', 'topic'),
('United Arab Emirates Real Estate', 'متحدہ عرب امارات جائیداد', 'united-arab-emirates-real-estate', 'topic'),
('United Arab Emirates Islamic', 'متحدہ عرب امارات اسلامی', 'united-arab-emirates-islamic', 'topic'),
('Saudi Arabia Friendship', 'سعودی عرب دوستی', 'saudi-arabia-friendship', 'topic'),
('Saudi Arabia Jobs', 'سعودی عرب ملازمتیں', 'saudi-arabia-jobs', 'topic'),
('Saudi Arabia News', 'سعودی عرب خبریں', 'saudi-arabia-news', 'topic'),
('Saudi Arabia Education', 'سعودی عرب تعلیم', 'saudi-arabia-education', 'topic'),
('Saudi Arabia Business', 'سعودی عرب کاروبار', 'saudi-arabia-business', 'topic'),
('Saudi Arabia Sports', 'سعودی عرب کھیل', 'saudi-arabia-sports', 'topic'),
('Saudi Arabia Gaming', 'سعودی عرب گیمنگ', 'saudi-arabia-gaming', 'topic'),
('Saudi Arabia Status', 'سعودی عرب اسٹیٹس', 'saudi-arabia-status', 'topic'),
('Saudi Arabia Islamic', 'سعودی عرب اسلامی', 'saudi-arabia-islamic', 'topic'),
('Saudi Arabia Quran', 'سعودی عرب قرآن', 'saudi-arabia-quran', 'topic'),
('Egypt Friendship', 'مصر دوستی', 'egypt-friendship', 'topic'),
('Egypt Jobs', 'مصر ملازمتیں', 'egypt-jobs', 'topic'),
('Egypt News', 'مصر خبریں', 'egypt-news', 'topic'),
('Egypt Education', 'مصر تعلیم', 'egypt-education', 'topic'),
('Egypt Business', 'مصر کاروبار', 'egypt-business', 'topic'),
('Egypt Sports', 'مصر کھیل', 'egypt-sports', 'topic'),
('Egypt Gaming', 'مصر گیمنگ', 'egypt-gaming', 'topic'),
('Egypt Status', 'مصر اسٹیٹس', 'egypt-status', 'topic'),
('Egypt Football', 'مصر فٹبال', 'egypt-football', 'topic'),
('Egypt Islamic', 'مصر اسلامی', 'egypt-islamic', 'topic'),
('Turkey Friendship', 'ترکی دوستی', 'turkey-friendship', 'topic'),
('Turkey Jobs', 'ترکی ملازمتیں', 'turkey-jobs', 'topic'),
('Turkey News', 'ترکی خبریں', 'turkey-news', 'topic'),
('Turkey Education', 'ترکی تعلیم', 'turkey-education', 'topic'),
('Turkey Business', 'ترکی کاروبار', 'turkey-business', 'topic'),
('Turkey Sports', 'ترکی کھیل', 'turkey-sports', 'topic'),
('Turkey Gaming', 'ترکی گیمنگ', 'turkey-gaming', 'topic'),
('Turkey Status', 'ترکی اسٹیٹس', 'turkey-status', 'topic'),
('Turkey Football', 'ترکی فٹبال', 'turkey-football', 'topic'),
('Philippines Friendship', 'فلپائن دوستی', 'philippines-friendship', 'topic'),
('Philippines Jobs', 'فلپائن ملازمتیں', 'philippines-jobs', 'topic'),
('Philippines News', 'فلپائن خبریں', 'philippines-news', 'topic'),
('Philippines Education', 'فلپائن تعلیم', 'philippines-education', 'topic'),
('Philippines Business', 'فلپائن کاروبار', 'philippines-business', 'topic'),
('Philippines Sports', 'فلپائن کھیل', 'philippines-sports', 'topic'),
('Philippines Gaming', 'فلپائن گیمنگ', 'philippines-gaming', 'topic'),
('Philippines Status', 'فلپائن اسٹیٹس', 'philippines-status', 'topic'),
('Philippines OFW', 'فلپائن او ایف ڈبلیو', 'philippines-ofw', 'topic'),
('Mexico Friendship', 'میکسیکو دوستی', 'mexico-friendship', 'topic'),
('Mexico Jobs', 'میکسیکو ملازمتیں', 'mexico-jobs', 'topic'),
('Mexico News', 'میکسیکو خبریں', 'mexico-news', 'topic'),
('Mexico Education', 'میکسیکو تعلیم', 'mexico-education', 'topic'),
('Mexico Business', 'میکسیکو کاروبار', 'mexico-business', 'topic'),
('Mexico Sports', 'میکسیکو کھیل', 'mexico-sports', 'topic'),
('Mexico Gaming', 'میکسیکو گیمنگ', 'mexico-gaming', 'topic'),
('Mexico Status', 'میکسیکو اسٹیٹس', 'mexico-status', 'topic'),
('Mexico Football', 'میکسیکو فٹبال', 'mexico-football', 'topic'),
('Malaysia Friendship', 'ملائیشیا دوستی', 'malaysia-friendship', 'topic'),
('Malaysia Jobs', 'ملائیشیا ملازمتیں', 'malaysia-jobs', 'topic'),
('Malaysia News', 'ملائیشیا خبریں', 'malaysia-news', 'topic'),
('Malaysia Education', 'ملائیشیا تعلیم', 'malaysia-education', 'topic'),
('Malaysia Business', 'ملائیشیا کاروبار', 'malaysia-business', 'topic'),
('Malaysia Sports', 'ملائیشیا کھیل', 'malaysia-sports', 'topic'),
('Malaysia Gaming', 'ملائیشیا گیمنگ', 'malaysia-gaming', 'topic'),
('Malaysia Status', 'ملائیشیا اسٹیٹس', 'malaysia-status', 'topic'),
('Malaysia Islamic', 'ملائیشیا اسلامی', 'malaysia-islamic', 'topic'),
('South Africa Friendship', 'جنوبی افریقہ دوستی', 'south-africa-friendship', 'topic'),
('South Africa Jobs', 'جنوبی افریقہ ملازمتیں', 'south-africa-jobs', 'topic'),
('South Africa News', 'جنوبی افریقہ خبریں', 'south-africa-news', 'topic'),
('South Africa Education', 'جنوبی افریقہ تعلیم', 'south-africa-education', 'topic'),
('South Africa Business', 'جنوبی افریقہ کاروبار', 'south-africa-business', 'topic'),
('South Africa Sports', 'جنوبی افریقہ کھیل', 'south-africa-sports', 'topic'),
('South Africa Gaming', 'جنوبی افریقہ گیمنگ', 'south-africa-gaming', 'topic'),
('South Africa Status', 'جنوبی افریقہ اسٹیٹس', 'south-africa-status', 'topic'),
('South Africa Football', 'جنوبی افریقہ فٹبال', 'south-africa-football', 'topic'),
('Kenya Friendship', 'کینیا دوستی', 'kenya-friendship', 'topic'),
('Kenya Jobs', 'کینیا ملازمتیں', 'kenya-jobs', 'topic'),
('Kenya News', 'کینیا خبریں', 'kenya-news', 'topic'),
('Kenya Education', 'کینیا تعلیم', 'kenya-education', 'topic'),
('Kenya Business', 'کینیا کاروبار', 'kenya-business', 'topic'),
('Kenya Sports', 'کینیا کھیل', 'kenya-sports', 'topic'),
('Kenya Gaming', 'کینیا گیمنگ', 'kenya-gaming', 'topic'),
('Kenya Status', 'کینیا اسٹیٹس', 'kenya-status', 'topic'),
('Ghana Friendship', 'گھانا دوستی', 'ghana-friendship', 'topic'),
('Ghana Jobs', 'گھانا ملازمتیں', 'ghana-jobs', 'topic'),
('Ghana News', 'گھانا خبریں', 'ghana-news', 'topic'),
('Ghana Education', 'گھانا تعلیم', 'ghana-education', 'topic'),
('Ghana Business', 'گھانا کاروبار', 'ghana-business', 'topic'),
('Ghana Sports', 'گھانا کھیل', 'ghana-sports', 'topic'),
('Ghana Gaming', 'گھانا گیمنگ', 'ghana-gaming', 'topic'),
('Ghana Status', 'گھانا اسٹیٹس', 'ghana-status', 'topic'),
('Argentina Friendship', 'ارجنٹائن دوستی', 'argentina-friendship', 'topic'),
('Argentina Jobs', 'ارجنٹائن ملازمتیں', 'argentina-jobs', 'topic'),
('Argentina News', 'ارجنٹائن خبریں', 'argentina-news', 'topic'),
('Argentina Education', 'ارجنٹائن تعلیم', 'argentina-education', 'topic'),
('Argentina Business', 'ارجنٹائن کاروبار', 'argentina-business', 'topic'),
('Argentina Sports', 'ارجنٹائن کھیل', 'argentina-sports', 'topic'),
('Argentina Gaming', 'ارجنٹائن گیمنگ', 'argentina-gaming', 'topic'),
('Argentina Status', 'ارجنٹائن اسٹیٹس', 'argentina-status', 'topic'),
('Argentina Football', 'ارجنٹائن فٹبال', 'argentina-football', 'topic'),
('Colombia Friendship', 'کولمبیا دوستی', 'colombia-friendship', 'topic'),
('Colombia Jobs', 'کولمبیا ملازمتیں', 'colombia-jobs', 'topic'),
('Colombia News', 'کولمبیا خبریں', 'colombia-news', 'topic'),
('Colombia Education', 'کولمبیا تعلیم', 'colombia-education', 'topic'),
('Colombia Business', 'کولمبیا کاروبار', 'colombia-business', 'topic'),
('Colombia Sports', 'کولمبیا کھیل', 'colombia-sports', 'topic'),
('Colombia Gaming', 'کولمبیا گیمنگ', 'colombia-gaming', 'topic'),
('Colombia Status', 'کولمبیا اسٹیٹس', 'colombia-status', 'topic'),
('Colombia Football', 'کولمبیا فٹبال', 'colombia-football', 'topic'),
('Morocco Friendship', 'مراکش دوستی', 'morocco-friendship', 'topic'),
('Morocco Jobs', 'مراکش ملازمتیں', 'morocco-jobs', 'topic'),
('Morocco News', 'مراکش خبریں', 'morocco-news', 'topic'),
('Morocco Education', 'مراکش تعلیم', 'morocco-education', 'topic'),
('Morocco Business', 'مراکش کاروبار', 'morocco-business', 'topic'),
('Morocco Sports', 'مراکش کھیل', 'morocco-sports', 'topic'),
('Morocco Gaming', 'مراکش گیمنگ', 'morocco-gaming', 'topic'),
('Morocco Status', 'مراکش اسٹیٹس', 'morocco-status', 'topic'),
('Morocco Islamic', 'مراکش اسلامی', 'morocco-islamic', 'topic'),
('Nepal Friendship', 'نیپال دوستی', 'nepal-friendship', 'topic'),
('Nepal Jobs', 'نیپال ملازمتیں', 'nepal-jobs', 'topic'),
('Nepal News', 'نیپال خبریں', 'nepal-news', 'topic'),
('Nepal Education', 'نیپال تعلیم', 'nepal-education', 'topic'),
('Nepal Business', 'نیپال کاروبار', 'nepal-business', 'topic'),
('Nepal Sports', 'نیپال کھیل', 'nepal-sports', 'topic'),
('Nepal Gaming', 'نیپال گیمنگ', 'nepal-gaming', 'topic'),
('Nepal Status', 'نیپال اسٹیٹس', 'nepal-status', 'topic'),
('Sri Lanka Friendship', 'سری لنکا دوستی', 'sri-lanka-friendship', 'topic'),
('Sri Lanka Jobs', 'سری لنکا ملازمتیں', 'sri-lanka-jobs', 'topic'),
('Sri Lanka News', 'سری لنکا خبریں', 'sri-lanka-news', 'topic'),
('Sri Lanka Education', 'سری لنکا تعلیم', 'sri-lanka-education', 'topic'),
('Sri Lanka Business', 'سری لنکا کاروبار', 'sri-lanka-business', 'topic'),
('Sri Lanka Sports', 'سری لنکا کھیل', 'sri-lanka-sports', 'topic'),
('Sri Lanka Gaming', 'سری لنکا گیمنگ', 'sri-lanka-gaming', 'topic'),
('Sri Lanka Status', 'سری لنکا اسٹیٹس', 'sri-lanka-status', 'topic'),
('Sri Lanka Cricket', 'سری لنکا کرکٹ', 'sri-lanka-cricket', 'topic'),
('Iraq Friendship', 'عراق دوستی', 'iraq-friendship', 'topic'),
('Iraq Jobs', 'عراق ملازمتیں', 'iraq-jobs', 'topic'),
('Iraq News', 'عراق خبریں', 'iraq-news', 'topic'),
('Iraq Education', 'عراق تعلیم', 'iraq-education', 'topic'),
('Iraq Business', 'عراق کاروبار', 'iraq-business', 'topic'),
('Iraq Sports', 'عراق کھیل', 'iraq-sports', 'topic'),
('Iraq Gaming', 'عراق گیمنگ', 'iraq-gaming', 'topic'),
('Iraq Status', 'عراق اسٹیٹس', 'iraq-status', 'topic'),
('Iraq Islamic', 'عراق اسلامی', 'iraq-islamic', 'topic'),
('Germany Friendship', 'جرمنی دوستی', 'germany-friendship', 'topic'),
('Germany Jobs', 'جرمنی ملازمتیں', 'germany-jobs', 'topic'),
('Germany News', 'جرمنی خبریں', 'germany-news', 'topic'),
('Germany Education', 'جرمنی تعلیم', 'germany-education', 'topic'),
('Germany Business', 'جرمنی کاروبار', 'germany-business', 'topic'),
('Germany Sports', 'جرمنی کھیل', 'germany-sports', 'topic'),
('Germany Gaming', 'جرمنی گیمنگ', 'germany-gaming', 'topic'),
('Germany Status', 'جرمنی اسٹیٹس', 'germany-status', 'topic'),
('France Friendship', 'فرانس دوستی', 'france-friendship', 'topic'),
('France Jobs', 'فرانس ملازمتیں', 'france-jobs', 'topic'),
('France News', 'فرانس خبریں', 'france-news', 'topic'),
('France Education', 'فرانس تعلیم', 'france-education', 'topic'),
('France Business', 'فرانس کاروبار', 'france-business', 'topic'),
('France Sports', 'فرانس کھیل', 'france-sports', 'topic'),
('France Gaming', 'فرانس گیمنگ', 'france-gaming', 'topic'),
('France Status', 'فرانس اسٹیٹس', 'france-status', 'topic'),
('Spain Friendship', 'سپین دوستی', 'spain-friendship', 'topic'),
('Spain Jobs', 'سپین ملازمتیں', 'spain-jobs', 'topic'),
('Spain News', 'سپین خبریں', 'spain-news', 'topic'),
('Spain Education', 'سپین تعلیم', 'spain-education', 'topic'),
('Spain Business', 'سپین کاروبار', 'spain-business', 'topic'),
('Spain Sports', 'سپین کھیل', 'spain-sports', 'topic'),
('Spain Gaming', 'سپین گیمنگ', 'spain-gaming', 'topic'),
('Spain Status', 'سپین اسٹیٹس', 'spain-status', 'topic'),
('Spain Football', 'سپین فٹبال', 'spain-football', 'topic'),
('Italy Friendship', 'اٹلی دوستی', 'italy-friendship', 'topic'),
('Italy Jobs', 'اٹلی ملازمتیں', 'italy-jobs', 'topic'),
('Italy News', 'اٹلی خبریں', 'italy-news', 'topic'),
('Italy Education', 'اٹلی تعلیم', 'italy-education', 'topic'),
('Italy Business', 'اٹلی کاروبار', 'italy-business', 'topic'),
('Italy Sports', 'اٹلی کھیل', 'italy-sports', 'topic'),
('Italy Gaming', 'اٹلی گیمنگ', 'italy-gaming', 'topic'),
('Italy Status', 'اٹلی اسٹیٹس', 'italy-status', 'topic'),
('Italy Football', 'اٹلی فٹبال', 'italy-football', 'topic'),
('Ethiopia Friendship', 'ایتھوپیا دوستی', 'ethiopia-friendship', 'topic'),
('Ethiopia Jobs', 'ایتھوپیا ملازمتیں', 'ethiopia-jobs', 'topic'),
('Ethiopia News', 'ایتھوپیا خبریں', 'ethiopia-news', 'topic'),
('Ethiopia Education', 'ایتھوپیا تعلیم', 'ethiopia-education', 'topic'),
('Ethiopia Business', 'ایتھوپیا کاروبار', 'ethiopia-business', 'topic'),
('Ethiopia Sports', 'ایتھوپیا کھیل', 'ethiopia-sports', 'topic'),
('Ethiopia Gaming', 'ایتھوپیا گیمنگ', 'ethiopia-gaming', 'topic'),
('Ethiopia Status', 'ایتھوپیا اسٹیٹس', 'ethiopia-status', 'topic'),
('Tanzania Friendship', 'تنزانیہ دوستی', 'tanzania-friendship', 'topic'),
('Tanzania Jobs', 'تنزانیہ ملازمتیں', 'tanzania-jobs', 'topic'),
('Tanzania News', 'تنزانیہ خبریں', 'tanzania-news', 'topic'),
('Tanzania Education', 'تنزانیہ تعلیم', 'tanzania-education', 'topic'),
('Tanzania Business', 'تنزانیہ کاروبار', 'tanzania-business', 'topic'),
('Tanzania Sports', 'تنزانیہ کھیل', 'tanzania-sports', 'topic'),
('Tanzania Gaming', 'تنزانیہ گیمنگ', 'tanzania-gaming', 'topic'),
('Tanzania Status', 'تنزانیہ اسٹیٹس', 'tanzania-status', 'topic');

INSERT INTO `groups` (name, invite_url, category_id, description, image_url, status) SELECT 'Demo Friendship Circle', 'https://chat.whatsapp.com/FAKEDemoFriend0001', id, 'This is a fake sample. It is not a real WhatsApp group. It is listed as an example on WhatsGrolink.com.', NULL, 'approved' FROM categories WHERE slug = 'friendship';
INSERT INTO `groups` (name, invite_url, category_id, description, image_url, status) SELECT 'Demo Study Room', 'https://chat.whatsapp.com/FAKEDemoEducat0002', id, 'This is a fake sample. It is not a real WhatsApp group. It is listed as an example on WhatsGrolink.com.', NULL, 'approved' FROM categories WHERE slug = 'education';
INSERT INTO `groups` (name, invite_url, category_id, description, image_url, status) SELECT 'Demo Jobs Board', 'https://chat.whatsapp.com/FAKEDemoJobsBo0003', id, 'This is a fake sample. It is not a real WhatsApp group. It is listed as an example on WhatsGrolink.com.', NULL, 'approved' FROM categories WHERE slug = 'jobs';
INSERT INTO `groups` (name, invite_url, category_id, description, image_url, status) SELECT 'Demo Quran Reminder', 'https://chat.whatsapp.com/FAKEDemoIslamic004', id, 'This is a fake sample. It is not a real WhatsApp group. It is listed as an example on WhatsGrolink.com.', NULL, 'approved' FROM categories WHERE slug = 'islamic';
INSERT INTO `groups` (name, invite_url, category_id, description, image_url, status) SELECT 'Demo Sports Talk', 'https://chat.whatsapp.com/FAKEDemoSports0005', id, 'This is a fake sample. It is not a real WhatsApp group. It is listed as an example on WhatsGrolink.com.', NULL, 'approved' FROM categories WHERE slug = 'sports';
INSERT INTO categories (name, name_ur, slug, kind, is_adult) VALUES ('18+', NULL, '18-plus', 'topic', 1);

INSERT INTO `groups` (name, invite_url, category_id, description, image_url, status) SELECT 'Demo Tech Chat', 'https://chat.whatsapp.com/FAKEDemoTechnol006', id, 'This is a fake sample. It is not a real WhatsApp group. It is listed as an example on WhatsGrolink.com.', NULL, 'approved' FROM categories WHERE slug = 'technology';
INSERT INTO `groups` (name, invite_url, category_id, description, image_url, status) SELECT 'Adult sample', 'https://chat.whatsapp.com/FAKEDemoAdult00007', id, 'This is a fake sample. It is not a real WhatsApp group. It is listed as an example on WhatsGrolink.com.', NULL, 'approved' FROM categories WHERE slug = '18-plus';
